### ISSUE TITLE
Error with command: jamstack t html5up/massively myproject --existing

### ISSUE THREAD

**Issue by mohamedmehdigara** [jamstackpy/jamstack#1]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts\jamstack.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jamstack\__main__.py", line 59, in main
    cli()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 782, in main    rv = self.invoke(ctx)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1259, in inv    return _process_result(sub_ctx.command.invoke(sub_ctx))
fra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jamstack\__main__.py", line 48, in t
    os.path.join(sites_path, templates[template]),
KeyError: 'html5up/massively'
PS C:\Users\Admin\Downloads\jamstack> python static.py
C:\Python27\python.exe: can't open file 'static.py': [Errno 2] No such file or directory 
PS C:\Users\Admin\Downloads\jamstack> python setup.py
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    with open(os.path.join(here, "README.md"), encoding="utf-8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by Jalkhov** [comment]
Hi @mohamedmehdigara 

I think you followed the old instructions, we are moving repo and had not changed the default branch (which has outdated instructions), these are the new instructions:

`jamstack t massively myproject --existing`.

Anyway, the repo has been updated and you can see the new instructions in more detail.

**Comment by mohamedmehdigara** [comment]
@Jalkhov Hi. All is done. Thank you :)

**Comment by Jalkhov** [comment]
@mohamedmehdigara Your welcome n.n
